app:
  name: "TikTok Mini Mall"

user:
  ip: "localhost"
  port: ":50051"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

product:
  ip: "localhost"
  port: ":50052"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

cart:
  ip: "localhost"
  port: ":50053"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

shop:
  ip: "localhost"
  port: ":50054"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  ip: "localhost"
  port: ":6379"
  db: "9"
  password: "123456"

rocketmq:
  endpoint: "localhost:8081"
  access_key: "xxxxxx"
  secret_key: "xxxxxx"
  topic_prod: "topic_prod"