app:
  name: "TikTok Mini Mall"

gateway:
  ip: "localhost"
  port: ":8080"

user:
  ip: "localhost"
  port: ":50051"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

product:
  ip: "localhost"
  port: ":50052"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

cart:
  ip: "localhost"
  port: ":50053"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

shop:
  ip: "localhost"
  port: ":50054"
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/tiktok_mini_mall?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  ip: "localhost"
  port: ":6379"
  db: "9"
  password: "123456"

rocketmq:
  endpoint: "localhost:8081"
  access_key: "xxxxxx"
  secret_key: "xxxxxx"
  topic_prod: "topic_prod"

nacos:
  ip: "localhost"
  port: 8848
  log_dir: "/tmp/nacos/log"
  cache_dir: "/tmp/nacos/cache"
  timeout_ms: 5000
  namespace_id: ""

elasticsearch:
  host: "localhost"
  username: "elastic"
  password: ""